import { CheckCircle2, RotateCcw, Sparkles, Target } from 'lucide-react'
import { useState } from 'react'
import { Button, Card, Chip } from '../components/ui'

const actions = ['Fold', 'Call', 'Raise', 'Push']
export default function TrainingPage(): React.JSX.Element {
  const [answer, setAnswer] = useState<string | null>(null)
  const correct = answer === 'Raise'
  return <div className="page training-page"><header className="training-header"><p className="eyebrow">Centro de treinamento</p><h1>Treine a decisão, não a sorte.</h1><p>Cenários curtos para criar reflexos sólidos antes das mesas.</p></header><div className="training-stats"><span><Target size={16} /> Precisão hoje: 80%</span><span><Sparkles size={16} /> +50 XP por acerto</span></div><Card className="hand-trainer"><div className="hand-trainer__top"><div><p className="eyebrow">Situação #01 · Open raise</p><h2>O que faz?</h2></div><Chip active>Pré-flop</Chip></div><section className="poker-table" aria-label="Informações da mão"><div className="poker-seat poker-seat--top">CO<br /><strong>31 BB</strong></div><div className="poker-seat poker-seat--left">SB<br /><strong>18 BB</strong></div><div className="poker-seat poker-seat--right">BB<br /><strong>26 BB</strong></div><div className="hero-hand"><span>BTN</span><strong>22 BB</strong><div><i>A♦</i><i>J♠</i></div></div><p>Todos foldaram até você.</p></section><div className="training-options" role="radiogroup" aria-label="Escolha sua ação">{actions.map((action) => <button key={action} role="radio" aria-checked={answer === action} disabled={answer !== null} className={`${answer === action ? 'training-option--selected ' : ''}${answer !== null && action === 'Raise' ? 'training-option--correct' : ''}`} onClick={() => setAnswer(action)}>{action}</button>)}</div>{answer && <div className={correct ? 'training-feedback training-feedback--success' : 'training-feedback'}><CheckCircle2 size={20} /><div><strong>{correct ? 'Boa decisão: Raise.' : 'Vamos revisar essa linha.'}</strong><p>Com 22 BB no botão, A♦J♠ está claramente no seu range de open raise. Você tem posição, uma mão forte e pode aplicar pressão nos blinds. Call perde iniciativa; push arrisca mais fichas do que o necessário.</p></div></div>}{answer && <Button variant="secondary" className="reset-training" onClick={() => setAnswer(null)}><RotateCcw size={16} /> Tentar novo cenário</Button>}</Card></div>
}
