import { CheckCircle2, Clock3, Flame, RotateCcw, Sparkles, Target, XCircle } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import TrainingFilters from '../features/training/components/TrainingFilters'
import { getNextSituation, getSituations } from '../features/training/services/situationService'
import type { TrainingAction, TrainingSituation } from '../features/training/types'
import { useTrainingStore } from '../stores/trainingStore'
import { Badge, Button, Card, Chip, ProgressBar } from '../components/ui'

const actionLabels: Record<TrainingAction, string> = { fold: 'Fold', limp: 'Limp', call: 'Call', raise: 'Raise', push: 'Push' }
const actionOrder: TrainingAction[] = ['fold', 'limp', 'raise', 'push']
const formatTime = (seconds: number): string => `${Math.floor(seconds / 60)}m ${seconds % 60}s`

function StatBoard(): React.JSX.Element {
  const { stats } = useTrainingStore(); const accuracy = stats.resolved ? Math.round((stats.correct / stats.resolved) * 100) : 0
  return <section className="training-stat-board" aria-label="Seu desempenho no treino"><div><Target size={18} /><span>Situações<strong>{stats.resolved}</strong></span></div><div><CheckCircle2 size={18} /><span>Taxa de acerto<strong>{accuracy}%</strong></span></div><div><Flame size={18} /><span>Sequência<strong>{stats.streak}</strong></span></div><div><Sparkles size={18} /><span>XP no treino<strong>{stats.xp}</strong></span></div><div><Clock3 size={18} /><span>Tempo treinando<strong>{formatTime(stats.secondsTrained)}</strong></span></div></section>
}

function SituationTable({ situation }: { situation: TrainingSituation }): React.JSX.Element { return <section className="poker-table poker-table--dynamic" aria-label="Situação atual"><div className="poker-seat poker-seat--top">{situation.villains[0]?.position ?? 'CO'}<br /><strong>{situation.villains[0]?.stack ?? 30} BB</strong><small>{situation.villains[0]?.description}</small></div><div className="poker-seat poker-seat--left">{situation.villains[1]?.position ?? 'SB'}<br /><strong>{situation.villains[1]?.stack ?? 20} BB</strong><small>{situation.villains[1]?.description}</small></div><div className="poker-seat poker-seat--right">BB<br /><strong>26 BB</strong></div><div className="hero-hand"><span>{situation.position}</span><strong>{situation.stack} BB</strong><div>{situation.heroCards.map((card) => <i key={card} className={card.includes('♦') || card.includes('♥') ? 'poker-card poker-card--red' : 'poker-card'}>{card}</i>)}</div></div><p>{situation.actionContext}</p></section> }

export default function TrainingPage(): React.JSX.Element {
  const { filters, setFilters, recordAnswer } = useTrainingStore(); const situations = useMemo(() => getSituations(filters), [filters]); const [situation, setSituation] = useState<TrainingSituation | undefined>(() => getNextSituation(filters)); const [answer, setAnswer] = useState<TrainingAction | null>(null); const startedAt = useRef(Date.now())
  useEffect(() => { setSituation(getNextSituation(filters)); setAnswer(null); startedAt.current = Date.now() }, [filters])
  if (!situation) return <div className="page training-page"><header className="training-header"><p className="eyebrow">Centro de treinamento</p><h1>Escolha um filtro para começar.</h1></header><TrainingFilters filters={filters} onChange={setFilters} /><Card className="empty-training"><p>Nenhuma situação corresponde a esses filtros. Ajuste uma opção para encontrar novos spots.</p><Button onClick={() => setFilters({ positions: [], stacks: [], categories: [] })}>Limpar filtros</Button></Card></div>
  const correct = answer === situation.correctAction
  const submit = (action: TrainingAction): void => { if (answer) return; setAnswer(action); recordAnswer(action === situation.correctAction, situation.xpReward, Math.round((Date.now() - startedAt.current) / 1000)) }
  const next = (): void => { setSituation(getNextSituation(filters, situation.id)); setAnswer(null); startedAt.current = Date.now() }
  return <div className="page training-page"><header className="training-header"><div><p className="eyebrow">Centro de treinamento</p><h1>Treine a decisão, não a sorte.</h1><p>Cenários curtos, feedback imediato e progresso que acompanha sua evolução.</p></div><Badge tone="success">Pré-Flop</Badge></header><StatBoard /><TrainingFilters filters={filters} onChange={setFilters} /><div className="training-main"><Card className="hand-trainer"><div className="hand-trainer__top"><div><p className="eyebrow">Situação {situation.id.split('-').slice(0, 2).join(' · ')} </p><h2>O que você faz?</h2></div><Chip active>{situation.category === 'three-bet' ? '3Bet' : situation.category === 'push-fold' ? 'Push/Fold' : 'Open Raise'}</Chip></div><SituationTable situation={situation} /><div className="training-options" role="radiogroup" aria-label="Escolha sua ação">{actionOrder.map((action) => <button key={action} role="radio" aria-checked={answer === action} disabled={answer !== null} className={`${answer === action ? 'training-option--selected ' : ''}${answer !== null && action === situation.correctAction ? 'training-option--correct' : ''}${answer === action && !correct ? 'training-option--wrong' : ''}`} onClick={() => submit(action)}>{actionLabels[action]}</button>)}</div>{answer && <section className={correct ? 'training-feedback training-feedback--success' : 'training-feedback'} aria-live="polite">{correct ? <CheckCircle2 size={22} /> : <XCircle size={22} />}<div><strong>{correct ? `Correto! +${situation.xpReward} XP` : 'Ainda não. Vamos aprender com este spot.'}</strong><p>{situation.explanation}</p><div className="feedback-concepts"><span>Conceitos</span>{situation.concepts.map((concept) => <Badge key={concept} tone="success">{concept}</Badge>)}</div><div className="when-changes"><strong>Quando a resposta mudaria?</strong><p>{situation.whenItChanges}</p></div></div></section>}{answer && <Button className="next-situation" onClick={next}>Próxima situação <RotateCcw size={16} /></Button>}</Card><aside className="training-aside"><Card className="training-insight"><Sparkles size={20} /><p className="eyebrow">Aprendizado ativo</p><h2>Decida. Entenda. Repita.</h2><p>Seu desempenho é registrado localmente para que cada sessão mostre uma evolução concreta.</p></Card><Card className="training-chart"><p className="eyebrow">Precisão recente</p><div className="chart-bars" aria-label="Gráfico de acertos recentes">{[42, 58, 51, 74, 68, 82, 90].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><span>Últimas 7 decisões</span><ProgressBar value={situations.length ? 100 : 0} label="Cobertura de situações do filtro" /></Card></aside></div></div>
}
