import { useId, useState, type ButtonHTMLAttributes, type PropsWithChildren, type ReactNode } from 'react'

export function Button({ variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' }): React.JSX.Element { return <button className={`ui-button ui-button--${variant} ${className}`} {...props} /> }
export function Card({ children, className = '' }: PropsWithChildren<{ className?: string }>): React.JSX.Element { return <section className={`ui-card ${className}`}>{children}</section> }
export function Badge({ children, tone = 'default' }: PropsWithChildren<{ tone?: 'default' | 'success' | 'warning' }>): React.JSX.Element { return <span className={`ui-badge ui-badge--${tone}`}>{children}</span> }
export function Chip({ children, active = false, onClick }: PropsWithChildren<{ active?: boolean; onClick?: () => void }>): React.JSX.Element { return <button className={`ui-chip ${active ? 'ui-chip--active' : ''}`} onClick={onClick}>{children}</button> }
export function ProgressBar({ value, label }: { value: number; label?: string }): React.JSX.Element { const safeValue = Math.min(100, Math.max(0, value)); return <div className="ui-progress" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={safeValue}><span style={{ width: `${safeValue}%` }} /></div> }
export function Tooltip({ label, children }: PropsWithChildren<{ label: string }>): React.JSX.Element { return <span className="ui-tooltip" data-tooltip={label}>{children}</span> }
export function Modal({ open, title, onClose, children }: PropsWithChildren<{ open: boolean; title: string; onClose: () => void }>): React.JSX.Element | null { if (!open) return null; return <div className="ui-modal-backdrop" role="presentation" onMouseDown={onClose}><section className="ui-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><header><h2>{title}</h2><Button variant="ghost" onClick={onClose} aria-label="Fechar">×</Button></header>{children}</section></div> }
export function Accordion({ items }: { items: { title: string; content: ReactNode }[] }): React.JSX.Element { const [open, setOpen] = useState<number | null>(0); return <div className="ui-accordion">{items.map((item, index) => <section key={item.title}><button onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}>{item.title}<span>⌄</span></button>{open === index && <div>{item.content}</div>}</section>)}</div> }
export function Tabs({ tabs, active, onChange }: { tabs: string[]; active: string; onChange: (tab: string) => void }): React.JSX.Element { return <div className="ui-tabs" role="tablist">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={tab === active} onClick={() => onChange(tab)}>{tab}</button>)}</div> }
export function Avatar({ name }: { name: string }): React.JSX.Element { return <span className="ui-avatar" aria-label={`Perfil de ${name}`}>{name.slice(0, 1).toUpperCase()}</span> }
export function Alert({ children, tone = 'info' }: PropsWithChildren<{ tone?: 'info' | 'success' | 'warning' }>): React.JSX.Element { const id = useId(); return <div id={id} className={`ui-alert ui-alert--${tone}`} role="status">{children}</div> }
